Repository Team-QSS/KonoPuro-Unity, pull requests merged in 2024-06, with the labels that each got.

#32 🔀 :: #30 #31 Add Gacha Skip
  Assets/Scenes/CardGatchaMulti.unity
  Assets/Scenes/CardGatchaSingle.unity
  Assets/Scenes/GachaDirectingStartScene.unity
  Assets/_root/Material/GachaDirecting.meta
  Assets/_root/Material/GachaDirecting/Scene.anim
  Assets/_root/Script/Card/GachaDirectionColor.cs
  Assets/_root/Script/Card/GachaDirectionColor.cs.meta
  Assets/_root/Script/Card/GachaMultiCardSetter.cs
  Assets/_root/Script/Card/GachaSingleCardSetter.cs
  Assets/_root/Script/Main/GachaUI.cs
  Assets/cardinrange/CardinrandomRange.cs
  Assets/cardinrange/ExitGatcha.cs
Labels: 새 기능, 업데이트

#34 Convert blend to fbx
  Assets/Resources/Audio/CLICKED.wav
  Assets/Resources/Audio/CLICKED.wav.meta
  Assets/Resources/Audio/GAME_START.wav
  Assets/Resources/Audio/GAME_START.wav.meta
  Assets/Resources/Audio/SELECTED.wav
  Assets/Resources/Audio/SELECTED.wav.meta
  Assets/Scenes/GachaDirectingStartScene.unity
  Assets/Scenes/MainScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/_root/Audio.meta
  Assets/_root/Audio/PURO_BUILDUP.wav.meta
  Assets/_root/Audio/PURO_LOOP.wav
  Assets/_root/Audio/PURO_LOOP.wav.meta
  Assets/_root/Material/GachaDirecting/MacBook_Air_13_.blend.meta
  Assets/_root/Material/GachaDirecting/MacBook_Air_13_.fbx.meta
  Assets/_root/Script/Main/MainManager.cs
  Assets/_root/Script/Manager/AudioManager.cs
  Assets/_root/Script/Manager/AudioManager.prefab
  Assets/_root/Script/Title/TitleManager.cs
Labels: 리팩토링

#56 🔀:: #55 Fix NewLine Error
  Assets/Scenes/MainScene.unity
  Assets/Scenes/TitleScene.unity
Labels: 버그, 리팩토링, 업데이트

#59 🔀:: #58 회원가입을 성공적으로 한 이후 즉시 로그인 화면으로 이동하도록 변경
  Assets/_root/Script/Title/AuthPanel.cs
  Assets/_root/Script/Title/TitleManager.cs
Labels: 업데이트

#57 카드 사용 연출(이름, 사용자 표시)
  Assets/Scenes/IngameScene.unity
  Assets/_root/Animation/CardUseage.anim
  Assets/_root/Animation/CardUseage.anim.meta
  Assets/_root/Animation/CardUseagePanel.controller
  Assets/_root/Animation/CardUseagePanel.controller.meta
  Assets/_root/Prefabs/CardUseagePanel.prefab
  Assets/_root/Prefabs/CardUseagePanel.prefab.meta
  Assets/_root/Script/Ingame/IngameManager.cs
  Assets/_root/Script/Ingame/IngameUi.cs
  Assets/_root/Script/Ingame/PlayerActivity.cs
  Assets/_root/Script/Ingame/SelectionModeUi.cs
  Assets/_root/Script/Ingame/TurnDisplayDefault.cs
  Assets/_root/Script/Ingame/TurnDisplayDefault.cs.meta
  Assets/_root/Script/Main/CinemacineController.cs
  Assets/_root/Sprite/CardUseagePanel.png
  Assets/_root/Sprite/CardUseagePanel.png.meta
  ProjectSettings/TagManager.asset
Labels: 업데이트, 최적화

#70 🔀:: #69 오늘의 카드 위치 수정
  Assets/Scenes/TitleScene.unity
Labels: 리팩토링

#75 🔀:: 랜덤 오류 해결
  Assets/cardinrange/SpriteArray.cs
Labels: 버그 수정, 업데이트

#72 🔀:: #71 로그아웃 버튼 이미지 추가
  Assets/Scenes/TitleScene.unity
  Assets/_root/Sprites/Login.png
  Assets/_root/Sprites/Login.png.meta
  Assets/_root/Sprites/Logout.png
  Assets/_root/Sprites/Logout.png.meta
Labels: 버그 수정, 리소스

#76 🔀카드연출 chayoungbranch
  Assets/Scenes/MainScene.unity
  Assets/UnityTechnologies/ParticlePack/Shared/Scripts/ShowPlayerGold.cs
  Assets/UnityTechnologies/ParticlePack/Shared/Scripts/ShowPlayerGold.cs.meta
Labels: 업데이트

#79 🔀:: #68 #67 사용하지 않는 씬 삭제
  Assets/Scenes/DeckEditTable.unity
  Assets/Scenes/DeckEditTable.unity.meta
  Assets/Scenes/GachaScene.unity
  Assets/Scenes/GachaScene.unity.meta
  Assets/Scenes/GachaUI.unity
  Assets/Scenes/GachaUI.unity.meta
  Assets/Scenes/MainScene 1.unity
  Assets/Scenes/MainScene 1.unity.meta
Labels: 리팩토링, 업데이트

#81 🔀:: #80 스플래시 이미지 추가
  Assets/_root/Sprite/TeamQSS Presents 1.png
  Assets/_root/Sprite/TeamQSS Presents 1.png.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: 리소스, 새 기능

#83 🔀:: #82 스플래시 이미지 업스케일링
  Assets/_root/Sprite/TeamQSS Presents 1.png
Labels: 리소스, 업데이트

#85 🔀:: 카드 필터링 이슈 & 카드 셰이더 수정
  Assets/Scenes/MainScene.unity
  Assets/_root/Prefabs/Ui/DeckEditMenu.prefab
  Assets/_root/Script/Main/Deck/DeckEditMenu.cs
  Assets/_root/Shader/Card/CardBackSide.shadergraph
  Assets/_root/Shader/Card/CardFrontSide.shadergraph
Labels: 버그 수정

#89 🔀:: #88 설정창 이미지 추가 및 위치 수정
  Assets/Config.json
  Assets/Scenes/MainScene.unity
  Assets/_root/Prefabs/Ui/ConfigMenu.prefab
  Assets/_root/Script/Config/ConfigInUI.cs
  Assets/_root/Sprites/Setting.png
  Assets/_root/Sprites/Setting.png.meta
Labels: 버그 수정, 리소스, 업데이트

#93 🔀:: #92 #94 버그 수정 및 리팩토링
  Assets/Resources/Card/CF.png
  Assets/Scenes/GachaDirectingStartScene.unity
  Assets/Scenes/GachaDirectingStartScene_Profiles.meta
  Assets/Scenes/GachaDirectingStartScene_Profiles/MacBook_Air_13_ Profile.asset
  Assets/Scenes/GachaDirectingStartScene_Profiles/MacBook_Air_13_ Profile.asset.meta
  Assets/UnityTechnologies/ParticlePack/Shared/Scripts/ShowPlayerGold.cs
  Assets/_root/Material/GachaDirecting/Scene.anim
  Assets/_root/Script/Card/GachaBuildup.cs
  Assets/_root/Script/Client/RawProtocol.cs
  Assets/_root/Script/Config/ConfigButton.cs
  Assets/_root/Script/Config/ConfigInUI.cs
  Assets/_root/Script/Config/ConfigManager.cs
  Assets/_root/Script/Config/Setting.cs
  Assets/_root/Script/Config/SoundVolumeManager.cs
  Assets/_root/Script/Config/SoundVolumeManager.cs.meta
  Assets/_root/Script/Config/UserInfoPanel.cs
  Assets/_root/Script/Ingame/DescriptionUI.cs
  Assets/_root/Script/Ingame/DescriptionUI.cs.meta
  Assets/_root/Script/Ingame/DiscriptionUI.cs
  Assets/_root/Script/Ingame/IngameManager.cs
  Assets/_root/Script/Ingame/IngameUi.cs
  Assets/_root/Script/Ingame/PlayerActivity.cs
  Assets/_root/Script/Main/MainManager.cs
  Assets/_root/Script/Main/PlaceableObject.cs
  Assets/_root/Script/Manager/AudioManager.cs
Labels: 버그 수정, 리소스, 리팩토링, 업데이트

#96 🔀:: #95 가챠씬 효과음 수정
  Assets/Resources/Audio/GACHA-1-INITAL.wav
  Assets/Resources/Audio/GACHA-1-INITAL.wav.meta
  Assets/Resources/Audio/GACHA-1-STARTUP.wav
  Assets/Resources/Audio/GACHA-1-STARTUP.wav.meta
  Assets/Resources/Audio/GACHA-1-WINDUP.wav
  Assets/Resources/Audio/GACHA-1-WINDUP.wav.meta
  Assets/Resources/Audio/GACHA-1.wav
  Assets/Scenes/NewScene/Hands.anim
  Assets/_root/Material/GachaDirecting/Scene.anim
  Assets/_root/Script/Card/GachaBuildup.cs
Labels: 리소스, 업데이트
